import Head from "next/head";
// import { useEffect } from "react";
import Header from "@/components/header/Header";
import Image from "next/image";

export default function Home() {

  return (
    <>
      <Head>
        <title>DecentraTap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-full overflow-x-hidden relative ">
        <Header />
        <main className="h-[90vh] overflow-hidden mt-[10vh] flex items-center justify-center">
          <div className="z-30 absolute h-5/6 w-10/12 blurEffect flex justify-between flex-row rounded-md p-10">
            <div className="w-6/12 h-full flex flex-col justify-center gap-10 items-center">
              <p className="text-white text-[72px] leading-[85px] font-bold">
                Discover, collect, and charity in extraordinary NFT marketplace
              </p>
              <p className="text-white text-lg ">
                In aenean posuere lorem risus nec. Tempor tincidunt aenean purus
                purus vestibulum nibh mi venenatis
              </p>
              <div className="w-full h-3/12 flex gap-9 items-center">
                <button className="background-gradient border-white transition-all duration-200  text-white text-lg rounded-xl  py-[1.5vh] px-[60px] ">
                  ثبت نام
                </button>
                <button className="bg-transparent border-[1px] border-white transition-all duration-200 text-white text-lg rounded-xl py-[1.5vh] px-[60px] ">
                  ورود
                </button>
              </div>
            </div>
            <div className="w-4/12 flex flex-col items-center justify-center">
              <div className="glass-main-card h-[80%] w-full ">
                <Image src="" className="rounded-[20px]" alt="video image" width={400} height={400}/>
              </div>

              
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
